version: '3'
services:
  postgres:
    image: postgres:14
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres